### ISSUE TITLE
Search box not working in published lessons

### ISSUE THREAD

**Issue by ocaisa** [carpentries/sandpaper#547] opened 2023-11-22 14:28 UTC
The search boxes in (at least):

* https://swcarpentry.github.io/shell-novice/
* https://swcarpentry.github.io/git-novice/
* https://swcarpentry.github.io/python-novice-inflammation/

do not work. Clicking on the search box (in Chrome and Firefox) does not allow you to write text, and the search button does not work.

**Comment by klbarnes20** [comment] 2023-11-22 14:46
Thank you for sharing this @ocaisa. Search is not currently operational in the workbench and is something we are working on. Please see #495 and https://github.com/carpentries/varnish/pull/86. Unfortunately, I cannot give you a timeline for when this will be operational, but know that it is on our radar.

**Comment by ocaisa** [comment] 2023-11-22 14:53
Thanks for the update, in terms of UX it may be better to hide the search bar for the time being until the feature is actually supported.

**Comment by zkamvar** [comment] 2023-11-22 14:55
Thank you. This is being discussed in https://github.com/carpentries/workbench/issues/8

We are aware of this problem and we are aware of the many potential solutions to it. I am going to close this issue as duplicate of the workbench issue.

**Closed by zkamvar** 2023-11-22 14:55 UTC
Labels: duplicate
