### ISSUE TITLE
Default setup fails with "[ENOENT] Failed to realize '': no such file or directory

### ISSUE THREAD

**Issue by LourensVeen** [carpentries/sandpaper#328] opened 2022-08-17 08:10 UTC
It seems that the default setup is currently broken. Having installed all the dependencies and the packages according to the documentation at https://carpentries.github.io/sandpaper-docs/#linux, the commands from the "Test your installation" section fail. In particular, `sandpaper::build_lesson(...)` fails with

```
Error: [ENOENT] Failed to realize '': no such file or directory
```

After some searching around, we managed to produce this poor excuse for a backtrace:

```
1: (function (..., call. = TRUE, domain = NULL) 
2: fs::path_real(import)
3: xml2::url_escape(fs::path_real(import), reserved = c("/:\\"))
4: get_stylesheet(stylesheet)
5: xml2::read_xml(get_stylesheet(stylesheet))
6: xml_to_md(q)
7: get_list_block(self, type = "questions", in_yaml = !private$mutations["move_questions"])
8: (function () 
9: paste(ep$questions, collapse = "\n")
10: FUN(X[[i]], ...)
11: lapply(episodes, get_questions)
12: get_syllabus(path, questions = TRUE)
13: gsub("\n", "<br/>", syl$questions)
14: format_syllabus(get_syllabus(path, questions = TRUE), use_col = FALSE)
15: build_home(pkg, quiet = quiet, sidebar = sidebar, new_setup = new_setup, 
16: build_site(path = path, quiet = quiet, preview = preview, override = override, 
17: sandpaper::build_lesson(tmp, preview = FALSE, quiet = FALSE)
```
Apologies for the lack of file names and line numbers, it seems that R is incapable of producing those.

After a lot of searching around, it seems to actually crash in `pegboard::get_syllabus`. Possibly the recent changes related to tinkr are the cause, it seems to be unable to load the tinkr stylesheet. The funny thing is that if I call get_stylesheet directly in the way that the vapply command does (at least to the extent that I understand vapply, the documentation is somewhat lacking), then it does work.

So that's about what I could figure out. Here are the installed versions of the most relevant packages:

```
R 3.6 (4.2 gives the same error)
pandoc 2.19
pegboard 0.2.6
pkgdown 2.0.6
sandpaper 0.9.3
tinkr 0.0.0.9003
```
I tried to install older and newer versions of tinkr and pegboard and sandpaper using the `githubinstall` R package, but that's also broken (it couldn't find the repository) so I didn't manage.

That's about all I could figure out, so I'm going to leave this here and hope it's enough information for someone to be able to fix this. Thanks in advance!

**Comment by zkamvar** [comment] 2022-08-17 15:30
Thank you for opening this issue and providing detailed feedback! I can confirm the issue you are having as I ran into it yesterday myself with [the error appearing on CI](https://github.com/carpentries/workbench-template-md/runs/7848600898?check_suite_focus=true#step:7:75) and locally:

``` r
sandpaper::build_lesson("~/Documents/Carpentries/Git/carpentries/sandpaper-docs")
#> Error: [ENOENT] Failed to realize '': no such file or directory
```

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23)
#>  os       Ubuntu 20.04.4 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language en_US:en
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Los_Angeles
#>  date     2022-08-17
#>  pandoc   2.12 @ /home/zhian/anaconda3/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  askpass       1.1     2019-01-13 [1] CRAN (R 4.0.0)
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.1)
#>  callr         3.7.1   2022-07-13 [1] RSPM (R 4.2.0)
#>  cli           3.3.0   2022-04-25 [1] CRAN (R 4.1.3)
#>  commonmark    1.8.0   2022-03-09 [1] CRAN (R 4.1.2)
#>  credentials   1.3.2   2021-11-29 [1] CRAN (R 4.1.2)
#>  DBI           1.1.3   2022-06-18 [1] RSPM (R 4.2.0)
#>  desc          1.4.1   2022-03-06 [1] CRAN (R 4.1.2)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.1.2)
#>  downlit       0.4.2   2022-07-05 [1] CRAN (R 4.2.1)
#>  dplyr         1.0.9   2022-04-28 [1] CRAN (R 4.2.0)
#>  evaluate      0.16    2022-08-09 [1] CRAN (R 4.2.1)
#>  fansi         1.0.3   2022-03-24 [1] CRAN (R 4.1.3)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.3)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
#>  generics      0.1.3   2022-07-05 [1] RSPM (R 4.2.0)
#>  gert          1.7.0   2022-08-07 [1] CRAN (R 4.2.1)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.1.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.5)
#>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.1)
#>  knitr         1.39.6  2022-08-08 [1] Github (yihui/knitr@bebf67e)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.1.3)
#>  memoise       2.0.1   2021-11-26 [1] CRAN (R 4.1.2)
#>  openssl       2.0.2   2022-05-24 [1] RSPM (R 4.2.0)
#>  pegboard      0.2.6   2022-08-10 [1] https://carpentries.r-universe.dev (R 4.2.1)
#>  pillar        1.8.0   2022-07-18 [1] CRAN (R 4.2.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.4)
#>  pkgdown       2.0.6   2022-07-16 [1] CRAN (R 4.2.1)
#>  processx      3.7.0   2022-07-07 [1] RSPM (R 4.2.0)
#>  ps            1.7.1   2022-06-18 [1] RSPM (R 4.2.0)
#>  purrr         0.3.4   2020-04-17 [1] RSPM (R 4.1.0)
#>  R.cache       0.16.0  2022-07-21 [1] RSPM (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] RSPM (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] RSPM (R 4.2.0)
#>  R.utils       2.12.0  2022-06-28 [1] CRAN (R 4.2.1)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
#>  renv          0.15.5  2022-05-26 [1] RSPM (R 4.2.0)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.0)
#>  rlang         1.0.4   2022-07-12 [1] RSPM (R 4.2.0)
#>  rmarkdown     2.14    2022-04-25 [1] RSPM (R 4.2.0)
#>  rprojroot     2.0.3   2022-04-02 [1] CRAN (R 4.1.3)
#>  sandpaper     0.9.3   2022-08-12 [1] local
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.2)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  styler        1.7.0   2022-03-13 [1] CRAN (R 4.1.2)
#>  sys           3.4     2020-07-23 [1] CRAN (R 4.0.4)
#>  tibble        3.1.8   2022-07-22 [1] RSPM (R 4.2.0)
#>  tidyselect    1.1.2   2022-02-21 [1] CRAN (R 4.1.2)
#>  tinkr         0.1.0   2022-08-15 [1] local
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
#>  varnish       0.2.4   2022-08-11 [1] local
#>  vctrs         0.4.1   2022-04-13 [1] CRAN (R 4.1.3)
#>  whisker       0.4     2019-08-28 [1] CRAN (R 4.0.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.1.2)
#>  xfun          0.32    2022-08-10 [1] CRAN (R 4.2.1)
#>  xml2          1.3.3   2021-11-30 [1] CRAN (R 4.1.2)
#>  yaml          2.3.5   2022-02-21 [1] CRAN (R 4.1.2)
#> 
#>  [1] /home/zhian/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

In short, you are 100% correct about your diagnosis: the problem was that pegboard did not properly update on the R universe repository (it should have been 0.3.1 to account for a [new version of {tinkr} containing a breaking change](https://github.com/ropensci/tinkr/pull/73/files#diff-51920e95310ebfbc1ae31709f3b95f89afffbf4f1a6e38e8b2b406e2fb6197eaR5), but only 0.2.6 was hosted). It has been fixed in https://github.com/r-universe-org/help/issues/190 and should now be available:

```r
install.packages("pegboard", repos = "https://carpentries.r-universe.dev")
```

> I tried to install older and newer versions of tinkr and pegboard and sandpaper using the githubinstall R package, but that's also broken (it couldn't find the repository) so I didn't manage.

Oh I've never seen the githubinstall package! It looks neat, but it also looks like it's abandoned as the database hasn't been updated since 2018: https://github.com/hoxo-m/githubinstall/issues/41

If you want to install any workbench package that's not on CRAN and the R-universe is down, you can also use our drat repository as a remote source: https://carpentries.github.io/drat/. This repo is updated twice per day (and I'll be sure to add that into the documentation)

**Closed** 2022-08-17 15:30 UTC
