### ISSUE TITLE
Bug: When referring to the same footnote multiple times, it works but the footnote is duplicated

### ISSUE THREAD

**Issue by apirogov** [carpentries/sandpaper#507] opened 2023-08-29 11:43 UTC
Example:

When one has markup such as

```
...
[^footnote]
....
[^footnote]

[^footnote]: Content of the footnote
```

the resulting HTML will have the footnote twice (with the same content), i.e. there will be two footnotes at the end, with different numbers:

```
1  Content of the footnote
2  Content of the footnote
```

Using [sandpaper (0.12.4)](https://github.com/carpentries/sandpaper/tree/0.12.4), [pegboard (0.5.3)](https://github.com/carpentries/pegboard/tree/0.5.3), and [varnish (0.2.18)](https://github.com/carpentries/varnish/tree/0.2.18).

**Comment by zkamvar** [comment] 2023-08-29 17:45
Hi @apirogov, thank you for creating the report. I can confirm that I also see this behaviour. Unfortunately, this is a behaviour that needs to be fixed in pandoc (see https://github.com/jgm/pandoc/issues/1603), which is a surprisingly difficult fix (see this comment: https://github.com/quarto-dev/quarto-cli/issues/5440#issuecomment-1550919788)

It may be possible to engineer a solution to post-process the footnotes by finding the footnote nodes that are identical in content and update their references, but there are many other things that need to take precedence right now as we are going to be losing a significant amount of capacity for project support when my funding runs out at the end of this year. 

I am going to close this as not planned since the fix should come from the pandoc side.

**Closed by zkamvar** 2023-08-29 17:45 UTC

**Comment by apirogov** [comment] 2023-08-30 09:26
It's okay, I agree that other things are more urgent + this is a downstream problem/behavior anyway. Thanks for the quick responses to the issues! 

As a headsup - I'm currently helping to fix some technical issues in an incubator course that make it fail to build after updating sandpaper, so a few more could be coming up.
