### ISSUE TITLE
Undescriptive error on building lesson

### ISSUE THREAD

**Issue by jhidding** [carpentries/sandpaper#622] opened 2024-11-20 13:28 UTC
The following error is given when building our [lesson on Efficient computing with Julia](https://github.com/esciencecenter-digital-skills/efficient-computing-in-julia).

```
> sandpaper::build_lesson()
...
-- Creating Instructor Notes -----------------------------------------
Error: Length of `path` must equal length of `new_path`
...
```

I couldn't find anything suspicious in the instructor notes, nor any obvious differences with the generated lesson template. I'm not sure how to recreate this from a newly created lesson (after `sandpaper::create_lesson("test")`).

**Comment by froggleston** [comment] 2024-11-21 14:33
Hi @jhidding - I'm wondering if this is because you have `overview.md` and `instructor-notes.md` in the instructors folder?

**Comment by jhidding** [comment] 2024-11-21 14:57
Yes! that solves it.

**Comment by froggleston** [comment] 2024-11-21 14:58
Great! I'll close this issue!

**Comment by jhidding** [comment] 2024-11-21 15:05
No don't! Why can there be only one file there? And why is the error so cryptic? Sandpaper has some serious usability issues (don't get me started on the installation). These things should be fixed not ignored.

**Comment by froggleston** [comment] 2024-11-21 15:37
Hi @jhidding - apologies, I wasn't intending to stifle any discussion, but keep the issues focused to specific topics. Please do raise issues that are specific to installation so that we can take a look at them. Similarly for usability we would always welcome suggestions for improvements.

I'm unsure why having two files there results in that message. The R traceback is also not very clear why the file copy fails (the error comes from the R `fs` package, and not the sandpaper code itself, but we're supplying some parameters to that function that seemingly it doesn't like. I can definitely try and add more useful error messaging in there as a first pass solution.

**Comment by froggleston** [comment] 2024-11-26 17:22
Hi @jhidding - I've had a chance to look through this some more, and the issue is that you have the `overview.md` and `instructor-notes.md` files in your `instructors/` folder, but only the `overview.md` listed in your `config.yaml`.

If you add the `instructor-notes.md` entry into your config, it should build:

```
# Information for Instructors
instructors:
- overview.md
- instructor-notes.md
```

I appreciate this error message is not useful at all, so now I know what the issue is, I can do a check and improve the error. I hope this helps.

**Closed** 2024-12-06 18:25 UTC
